set_property(GLOBAL PROPERTY USE_FOLDERS ON)



set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
 
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${ROOTPATH}/bin/debug)   

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${ROOTPATH}/bin/release)


source_group(TREE ${CMAKE_SOURCE_DIR} FILES ${HEAD_FILES})
source_group(TREE ${CMAKE_SOURCE_DIR} FILES ${SRC_FILES})
add_executable(${PROJECT_NAME} ${HEAD_FILES} ${SRC_FILES} ${MOC_FILES})